version: '3.8'
services:
  ripper:
    image: edgd1er/docker-ripper:latest
    container_name: ripper
    ports:
      - "9191:9090"
    environment:
      LOGIN: "john" # web ui login
      PASS: "doe"   # web ui pass
      PREFIX: ''    # web ui prefix
      DEBUG: 'False'
      TZ: "America/Chicago"
      MKV_KEY: "" # Makeversion registration key, if empty fetch beta key in mkv forum
      NOTIFICATION_ON: "n" #Optional, default n, activate notification whene ripped. (email, pushbullet, pushover)
      EMAIL_SENDER: 'YOUR_EMAIL'
      EMAIL_RECIPIENTS: 'DEST_EMAIL'
      EMAIL_PASSWORD: 'YOUR_PASSWORD'
      EMAIL_SERVER: 'smtp.gmail.com'
      EMAIL_SERVER_PORT: '587'
      EMAIL_DEBUG_LEVEL: '0'
      # Push notification parameters (Pushover)
      PUSHOVER_APP_TOKEN: 'YOUR_APP_TOKEN'
      USER_KEY: 'YOUR_USER_KEY'
      # Push notification parameters (Pushbullet)
      PUSHBULLET_APP_TOKEN: 'YOUR_APP_TOKEN'
      #NUID: 99 # optional, set new user id
      #NGID: 100 Optional, set new group id
    privileged: true # optional - only use when your drive is not detected inside the container
    volumes:
      - '/path/to/config/:/config:rw' # ripper conf
      - '/path/to/rips/:/out:rw'      # ripper's output dir.
    devices:
      - '/dev/sr0:/dev/sr0'
    secrets:
      - MKV_KEY

secrets:
  MKV_KEY:
    file: ./MKV_KEY
