name: Build ARM64 Image with MakeMKV from PPA

on:
#  schedule:
#    - cron: "0 0 * * 0"
#  push:
#    paths-ignore:
#      - 'manual-build/**'
  workflow_dispatch:

env:
  ENDPOINT: "rix1337/docker-ripper"

jobs:
  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKERUSER }}"
          password: "${{ secrets.DOCKERPASS }}"

      - name: Build and Push ARM64 Image
        uses: docker/build-push-action@v6
        with:
          context: "./"
          file: "./latest/Dockerfile"
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.ENDPOINT }}:latest-arm64
