name: check mkv version
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

env:
  MKVVERSION: 1.16.7

jobs:
  check-mkv_version:
    runs-on: ubuntu-latest
    steps:
      - name: get latest version
        id: getlatestversion
        run: |
          ver=$(curl -s "http://www.makemkv.com/download/" | grep -Eom1 "MakeMKV [0-9].[0-9]+\.[0-9]+" | sed 's/MakeMKV //')
          echo "mkv build version: ${{ env.MKVVERSION }}, latest mkv version: ${ver}"
          if [[ ${{ env.MKVVERSION }} != ${ver} ]]; then exit 1; fi

